name: CI

on:
  push:
    branches: ['detox']
  pull_request:
    branches: ['detox']
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ hashFiles('./yarn.lock') }}

      - name: yarn install --frozen-lockfile
        run: yarn install --frozen-lockfile

      - name: pod install
        working-directory: ios
        run: pod install
