name: CI

on:
  push:
    branches: ['appium']
  pull_request:
    branches: ['appium']
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps: 
      - uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ hashFiles('./yarn.lock') }}

      - name: Install node_modules
        run: yarn install --frozen-lockfile

      # - name: Cache Pods
      #   uses: actions/cache@v3
      #   with:
      #     path: ./ios/Pods
      #     key: ${{ hashFiles('./ios/Podfile.lock') }}

      # - name: Install Pods
      #   working-directory: ios
      #   run: pod install

      # - name: Cache build
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ./ios/build
      #       ~/Library/Developer/Xcode/DerivedData
      #     key: ${{ hashFiles('./ios/Podfile.lock') }}-v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Launch Metro bundler
        run: yarn start &

      - name: Run Appium server
        run: |
          yarn appium &
          until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/wd/hub/sessions); do
            sleep 5
          done

      - name: Run Android E2E tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: yarn build:android:debug && sleep 15 && yarn test:e2e:android:debug
